{{- if .Values.bffServer.enabled -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bff-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: bff-server
    name: bff
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff-server
      name: bff
  template:
    metadata:
      labels:
        app: bff-server
        name: bff
        version: v1
    spec:
      {{- if .Values.bffServer.hostConfig.enabled }}
      hostAliases: {{ toYaml .Values.bffServer.hostConfig.hostAliases | nindent 6 }}
      {{- end }}
      volumes:
        - name: time-localtime
          hostPath:
            path: /etc/localtime
            type: ''
        - name: oidc-server-ca
          secret:
            secretName: oidc-server-root-secret
            items:
            - key: ca.crt
              path: ca.crt
        - name: cluster-configs-secret
          secret:
            secretName: cluster-configs
        - name: portal-logos-volume
          configMap:
            name: portal-logos
        - name: portal-global-configs-volume
          configMap:
            name: portal-global-configs
        - name: bff-server-config-volume
          configMap:
            name: bff-server-config
      containers:
        - name: bff-server
          image: {{ .Values.registryServer }}/{{ .Values.bffServer.image }}
          livenessProbe:
            failureThreshold: 4
            httpGet:
              path: /bff/health
              port: 8022
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 4
            httpGet:
              path: /bff/health
              port: 8022
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          ports:
            - containerPort: 8022
              protocol: TCP
            - containerPort: 8023
              protocol: TCP
          env: # 主要是环境变量这里
            - name: redis_password
              valueFrom:
                secretKeyRef:
                  name: bff-secret
                  key: redis_password
            - name: basic_password
              valueFrom:
                secretKeyRef:
                  name: bff-secret
                  key: basic_password
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 512Mi
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: time-localtime
              readOnly: true
              mountPath: /etc/localtime
            - name: oidc-server-ca
              mountPath: /etc/oidc-server
              readOnly: true
            - mountPath: /usr/src/app/configs/cluster-configs
              name: cluster-configs-secret
              readOnly: true
            - mountPath: /usr/src/app/public/bff-public/profile/img
              name: portal-logos-volume
              readOnly: true
            - name: bff-server-config-volume
              mountPath: /usr/src/app/configs/config.yaml
              subPath: config.yaml
            - name: portal-global-configs-volume
              mountPath: /usr/src/app/configs/global-configs
              subPath: global-configs
---
apiVersion: v1
kind: Service
metadata:
  name: bff-server
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: bff-server
  ports:
    - protocol: TCP
      port: 8022
      name: http
      targetPort: 8022
    - protocol: TCP
      port: 8023
      name: websocket
      targetPort: 8023
---
apiVersion: v1
data:
kind: Secret
metadata:
  name: cluster-configs
  namespace: {{ .Release.Namespace }}
{{- end }}
