apiVersion: capsule.clastix.io/v1alpha1
kind: CapsuleConfiguration
metadata:
  annotations:
    capsule.clastix.io/enable-tls-configuration: "false"
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
  name: capsule-default
  namespace: {{ .Release.Namespace }}
spec:
  forceTenantPrefix: false
  protectedNamespaceRegex: ""
  userGroups:
  - capsule.clastix.io
  - iam.tenxcloud.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    capsule.clastix.io/enable-tls-configuration: "false"
  labels:
    control-plane: controller-manager
  name: capsule-controller-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --enable-leader-election
        - --zap-encoder=console
        - --configuration-name=capsule-default
        command:
        - /manager
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: {{ .Values.tenantManagement.image }}
        imagePullPolicy: IfNotPresent
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 8080
          name: metrics
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10080
        readinessProbe:
          httpGet:
            path: /readyz
            port: 10080
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: capsule-tls
