apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: capsule-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
  selector:
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  name: capsule-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: controller-manager
