{{- if .Values.iamProvider.enabled -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: iam-provider-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: oidc-server-root-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: iam-provider-certificate
  namespace: {{ .Release.Namespace }}
spec:
  duration: 87600h # the certificate expiration date is 10 years.
  renewBefore: 720h # renew certificate Before 1 month.
  secretName: iam-provider-secret
  dnsNames:
    - oidc-server
    - oidc-server.{{ .Release.Namespace }}.svc
  issuerRef:
    name: iam-provider-issuer
{{- end }}
