{{- if .Values.iamProvider.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: t7d.io.iam-provider
rules:
- apiGroups:
  - iam.tenxcloud.com
  resources:
  - users
  - groups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iam.tenxcloud.com
  resources:
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - iam.tenxcloud.com
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy
  resourceNames:
  - system
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
  - extensions
  resourceNames:
  - system
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
  - iam.tenxcloud.com
  resources:
  - connector3rds
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: t7d.io.iam-provider
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: t7d.io.iam-provider
subjects:
- kind: ServiceAccount
  name: oidc-server
  namespace: {{ .Release.Namespace }}
{{- end }}
