apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: t7d.io.{{ .Values.rbacResourceName }}
rules:
  - apiGroups:
      - capsule.clastix.io
    resources:
      - tenants
      - tenants/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "authentication.k8s.io"
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
    - policy
    resources:
    - podsecuritypolicies
    verbs:
    - create
    - delete
  - apiGroups:
    - ""
    resources:
    - configmaps
    resourceNames:
    - kubeadm-config
    verbs:
    - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: t7d.io.{{ .Values.rbacResourceName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: t7d.io.{{ .Values.rbacResourceName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbacResourceName }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbacResourceName }}
  namespace: {{ .Release.Namespace }}
{{- if semverCompare ">=1.24" .Capabilities.KubeVersion.Version }}
secrets:
  - name: {{ .Values.rbacResourceName }}-secret
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rbacResourceName }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.rbacResourceName }}
type: kubernetes.io/service-account-token
{{- end }}