apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: t7d.io.{{ .Values.clusterResPrefix }}-cluster-resource-reader
rules:
- apiGroups:
  - capsule.clastix.io
  resources:
  - tenants
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - extensions
  - policy
  resourceNames:
  - default
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: t7d.io.{{ .Values.clusterResPrefix }}-cluster-resource-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: t7d.io.{{ .Values.clusterResPrefix }}-cluster-resource-reader
subjects:
- kind: Group
  name: resource-reader
