apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oidc-proxy-certificate
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: oidc-proxy-certificate
  secretName: oidc-proxy-cert-tls
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
  - digital signature
  - key encipherment
  - server auth
  ipAddresses: {{ toYaml .Values.kubeOidcProxy.certificate.ipAddresses | nindent 4 }}
  dnsNames: {{ toYaml .Values.kubeOidcProxy.certificate.dnsNames | nindent 4 }}
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
