{{- if .Values.kubeOidcProxy.enabled -}}
apiVersion: v1
data:
  oidc.issuer-url: {{ b64enc .Values.kubeOidcProxy.issuerUrl }}
  oidc.username-claim: {{ b64enc .Values.kubeOidcProxy.usernameClaim }}
  oidc.group-claim: {{ b64enc .Values.kubeOidcProxy.groupClaim }}
  oidc.client-id: {{ b64enc .Values.kubeOidcProxy.clientId }}
kind: Secret
metadata:
  name: kube-oidc-proxy-config
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end }}
