# Default values for cluster-component.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Overwrite ingress-nginx chart template
ingress-nginx:
  enabled: true
  # MUST update this value
  deployedHost: &deployedHost <replaced-ingress-node-name>
  controller:
    ingressClassResource:
      name: portal-ingress
    ingressClass: portal-ingress
    image:
      repository: hub.tenxcloud.com/u4a-component/ingress-nginx-controller
      tag: "v1.3.0"
    admissionWebhooks:
      enabled: false
      patch:
        enabled: true
        image:
          registry: hub.tenxcloud.com
          image: u4a-component/kube-webhook-certgen
          tag: "0.30.0"
          digest: ""
    updateStrategy:
      type: Recreate
    extraArgs:
      update-status: false
      report-node-internal-ip-address: false
      http-port: 8080
      https-port: 8443
      enable-ssl-passthrough: true
      # it'll be 442 by default
      ssl-passthrough-proxy-port: 8442
    service:
      enabled: false
      type: ClusterIP
      internal:
        enabled: true
    config:
      use-gzip: "true"
      enable-vts-status: "true"
      large-client-header-buffers: 4 1m
      max-worker-connections: "65535"
      vts-default-filter-key: $server_name
      worker-processes: "4"
      http-snippet: |
        proxy_cache_path /tmp/bff-cache levels=1:2 keys_zone=static-cache:2m max_size=100m inactive=7d use_temp_path=off;
        proxy_cache_key $scheme$proxy_host$request_uri;
        proxy_cache_lock on;
        proxy_cache_use_stale updating;
    nodeSelector:
      kubernetes.io/os: linux
      # MUST update this value
      kubernetes.io/hostname: *deployedHost

cert-manager:
  enabled: true
  # Required: Cert manager for certificate management
  image: hub.tenxcloud.com/u4a-component/cert-manager-controller:v1.8.0
  caInjectorImage: hub.tenxcloud.com/u4a-component/cert-manager-cainjector:v1.8.0
  webhookImage: hub.tenxcloud.com/u4a-component/cert-manager-webhook:v1.8.0
